### PR TITLE
Find the Rez executable in the currently configured Xcode and pass it…

### PR DESCRIPTION
**Pull request by srussellextensis**
… to the dmg-license.py script to override the default location

### CODE REVIEW

**Comment by andreyvit** [comment]
Hey, I'd love to merge this, but is it always safe? What if Xcode is not installed?

**Comment by aonez** [comment]
@andreyvit I'm not familiar with that `Rez` binary, but the python script already uses it from Xcode:

https://github.com/andreyvit/create-dmg/blob/bcc07dd26bd12e024187d50449c184066b6b0765/support/dmg-license.py#L138-L144

So this code seems safe to me. Both `xrun` and `Rez` require at least the command line developer tools.

**Comment by aonez** [comment]
Will try to add this feature in the python script itself:
https://bitbucket.org/jaredhobbs/pyhacker/issues/2/check-default-rez-path

**Comment by jaredhobbs** [comment]
fixed in https://bitbucket.org/jaredhobbs/pyhacker/commits/e182f322e0f59c0786fe828dd055c14a21ecbdc9

**Pull request closed without merging**
