### PR TITLE
Use print() function in both Python 2 and 3

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by aonez** [comment]
It failed in Python 3?

**Comment by cclauss** [comment]
If any of these three lines are executed in Python 3 they will fail.  It is not clear to me if this script is ever run.

**Comment by aonez** [comment]
Ok just tested and python3 needs (). But I can't see where the import line is needed. It worked for me without that line in python 2.7 and 3.7.1. Where did you needed?

```py
from __future__ import print_function
```

**Comment by cclauss** [comment]
The import statement prevents Python 2 developers from breaking Python 3 code.

Try this...  Leave the import line in and add a Python 2 print statement _without_ the () and then try to run it on Python 2.  It will not work because with the import Python 2 will tell you that print without () is no longer allowed

**Pull request merged**
