### PR TITLE
Fixes issue with dmg size >1GB

### PR DESCRIPTION
**Pull request by mesouug**
Fixes issue with insufficient disk space when src dir is greater then 1GB;

### CODE REVIEW

**Comment by andreyvit** [comment]
Hey, I'd love to merge something like this, but can we make it conditional? Or at least can you explain why `resize` helps?

**Comment by mesouug** [comment]
That was really a while ago. As far as I remember it was working fine for small images ~100MB but it always failed for big images ~4GB. If you do just create with size specified initially it will create FS inside DMG a little smaller then specified size (that's why you have +20MB initially). But if you resize it afterwards it's actually make sures that you have specified size for FS inside DMG. I hope that I answered your question.

**Comment by aonez** [comment]
Testing this now with the Xcode.app (~12GB). It indeed failed. The temporary DMG was about 6GB.

**Comment by aonez** [comment]
This is actually not a bad idea. Not setting the size will make `hdiutil` estimate it's own size and not fail. After that, the size of the created DMG needs to be resized to accommodate the rest of the DMG resources.

The current size estimation using `du -sm` is very imprecise. Although using `du -s` and converting the blocks to B/MB is more precise, it also can fail (and failed in my tests with Xcode.app).

**Pull request closed without merging**
