### PR TITLE
Exit on AppleScript error

### PR DESCRIPTION
**Pull request by leominov**
* Exit on AppleScript error;
* Add .editorconfig;
* Fix codestyle.

### CODE REVIEW

**Comment by leominov** [comment]
I think there is no way to terminate script with AppleScript exit code:

```
#!/bin/bash

returnCode() {
    echo "$1" && return "$1"
}

echo "$(returnCode -1728) = $?"
echo "$(returnCode 1728) = $?"
echo "$(returnCode -10006) = $?"
echo "$(returnCode 10006) = $?"

# -1728 = 64
# 1728 = 192
# -10006 = 234
# 10006 = 22
```

So I stopped on code 64 as code for all AS problems.

**Comment by leominov** [comment]
It's about #45.

**Comment by GunArm** [comment]
@leominov thanks for this.  This is especially a problem since in order for this entire process to work a user has to be logged into the mac.
<rant>As for a million other reason Apple is hostile to development, in this case there's no official way to make good DMGs so people have to make hacky tools involving resizing windows with GUI macros.  And the hacky tool requires a user to be logged into the build-computer to work.  This makes the setup required for continuous integration a joke (can't virtualize a mac build machine on a PC, so lets buy a consumer mac-mini and set it on the floor in the server room next to the giant rack holding the VM servers that do everything else, oh and also, a user has to be logged into this headless machine to make builds)  No one in apple-land has has ever seen how big boys make software so this is where we land. </rant>
Anyway if a user is NOT logged into the headless-CI-build-node, the applescript fails, and without your changes, the command returns a success and the build looks good when it has failed miserably.  
It seems like this project has been abandoned so I kinda doubt this pull request will be merged but still I just wanted to say your changes work like a charm to fail builds on CI if the headless build node gets in a state where there's no dummy user logged in.  Thanks very much!

**Comment by andreyvit** [comment]
Hey, thanks! I'd love to merge this, but it's now conflicting because of the overall code changes. Can you please rebase?

**Comment by leominov** [comment]
Андрей, ёмаё, я уж не помню, что тут было 😆 но я гляну.

**Comment by aonez** [comment]
Implemented here 67f99bc478a4c71271888eab2aed6dd26878fdfc.

Thanks @leominov!

**Pull request closed without merging**
